name: build

on:
  pull_request:
    branches:
      - master
  release:
    types:
      [published]
  push:
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
  
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        id: release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

  compile:
    runs-on: ubuntu-latest
    container:
      image: alpine
    strategy:
      matrix:
        arch: [aarch64, ppc64le, riscv64, x86_64]
    
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        apk update  -U
        apk upgrade -U --available
        apk add     -U alpine-sdk git coreutils findutils ncurses-dev strace nano \
                      file patch less grep perl rsync bash zsh tcsh fish procps \
                      libtool autoconf automake groff bsd-compat-headers \
                      linux-headers util-linux python3 meson
        git config --global advice.detachedHead false

    - name: Build Static Lua
      run: |
        bash install.sh ${{ matrix.arch }}

    - name: Package Binaries
      run: |
        zip -r lua_static_${{ matrix.arch }}.zip modules
  
    - name: Upload Release Binaries
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: lua_static_${{ matrix.arch }}.zip
        asset_name: lua_static_${{ matrix.arch }}
